erDiagram
  lrdetails {
    VARCHAR ordno
    VARCHAR invno
    DATE invdate
    VARCHAR invref
    VARCHAR lrno
    DATE lrdate
    VARCHAR tname
    VARCHAR dpst
    VARCHAR cuno
    VARCHAR divcode
  }

  dpst_master {
    VARCHAR dpst_code
    VARCHAR dpst_desc
  }

  lr_details {
    VARCHAR invref
    VARCHAR invno
    INT company
    VARCHAR tname
    VARCHAR lrno
  }

  lrdetails }o--o| dpst_master : "dpst"
