erDiagram
  part_replaced_masters {
    INT id PK
    VARCHAR name
    VARCHAR status
    VARCHAR created_by
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  service_logs {
    INT id PK
    VARCHAR part_replaced
  }
