erDiagram
  industry_segments {
    INT id PK
    VARCHAR name
    VARCHAR status
    VARCHAR created_by
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  installed_base {
    INT id PK
    VARCHAR industry_segment
  }
