erDiagram
  reason_masters {
    INT id PK
    VARCHAR name
    VARCHAR status
    VARCHAR created_by
    TIMESTAMP created_at
    TIMESTAMP updated_at
    TIMESTAMP deleted_at
  }

  spare_parts_consumption_items {
    INT id PK
    VARCHAR reason
  }
