erDiagram
  product_master_vayu {
    INT id PK
    VARCHAR dpst
    VARCHAR product_group
    VARCHAR tplcode
    VARCHAR tpldesc
    VARCHAR dealer_price
    CHAR tod_flag
    CHAR excisable
    NUMERIC mc
    NUMERIC vc
    NUMERIC fc
    NUMERIC cos
    CHAR valid
    VARCHAR warehouse
    VARCHAR otcode
    INT company
    INT order_type
    VARCHAR status
    VARCHAR updated_by
    TIMESTAMP updated_date
  }
