-- Installed Base order references use pendingordersnew (dealerportal):
--   order_ref_id -> pendingordersnew.ordno (numeric ordno stored when possible)
--   order_id     -> pendingordersnew.ordno
--
-- If existing installed_base / service_logs rows were linked to the legacy
-- orders table, re-select the correct Vayu order or update order_ref_id manually.
