-- Replace all Industry Segment master data (IDs restart from 1).
-- Run: php sql/run_industry_segments_seed.php

TRUNCATE TABLE industry_segments RESTART IDENTITY;

INSERT INTO industry_segments (name, status, created_by) VALUES
    ('GENERAL ENGINEERING - MACHINING', 'active', 'system'),
    ('TEXTILES', 'active', 'system'),
    ('PAPER AND PULP', 'active', 'system'),
    ('FOUNDRY/FORGINGS', 'active', 'system'),
    ('GENERAL ENGINEERING - FABRICATION', 'active', 'system'),
    ('PHARMACEUTICALS', 'active', 'system'),
    ('DISTILLERIES/BREWERIES', 'active', 'system'),
    ('TRANSPORTATION', 'active', 'system'),
    ('AUTOMOBILE SERVICE STATIONS', 'active', 'system'),
    ('IRON AND STEEL', 'active', 'system'),
    ('GOVT TENDERS AND TENDERS', 'active', 'system'),
    ('RAILWAYS', 'active', 'system'),
    ('RESEARCH, TRAINING & EDUCATIONAL INSTITUTION', 'active', 'system'),
    ('CONSTRUCTION', 'active', 'system'),
    ('TELECOMMUNICATION', 'active', 'system'),
    ('POWER', 'active', 'system'),
    ('WW OEM DOMESTIC CUSTOMERS', 'active', 'system'),
    ('WW OE - INDIRECT EXPORT', 'active', 'system'),
    ('MINING', 'active', 'system'),
    ('GUNNETING, SHOT AND SAND BLASTING', 'active', 'system'),
    ('JACK HAMMER APPLICATION', 'active', 'system'),
    ('DRILLING OE''S', 'active', 'system'),
    ('MANUFACTURER (AUTOMOBILES)', 'active', 'system'),
    ('GRANITE MINING', 'active', 'system'),
    ('BLUE METAL QUARRY', 'active', 'system'),
    ('FOOD PROCESSING INDUSTRY.', 'active', 'system'),
    ('SHIPYARD/PORT', 'active', 'system'),
    ('PUBLISHING/PRINTING/PRESS.', 'active', 'system'),
    ('GENERAL ENGINEERING - FILTER MANUFACTURING', 'active', 'system'),
    ('CABLES', 'active', 'system'),
    ('CHEMICAL', 'active', 'system'),
    ('GENERAL ENGINEERING - MOTOR AND PUMPS', 'active', 'system'),
    ('PAINT', 'active', 'system'),
    ('PLASTIC', 'active', 'system'),
    ('Other Industry', 'active', 'system'),
    ('GENERAL ENGINEERING - TOOLS,DIE & FIXTURE ITEMS', 'active', 'system'),
    ('GENERAL ENGINEERING - INDUSTRIAL VALVES', 'active', 'system'),
    ('DYE & FERTILIZER', 'active', 'system'),
    ('TANNING/LEATHER PROCESING', 'active', 'system'),
    ('AGRI,FOOD STUFF &RELATED TECH', 'active', 'system'),
    ('CANNING/BOTTLING/PACKAGING', 'active', 'system'),
    ('METALLURGY', 'active', 'system'),
    ('AUTO ANCILLARY', 'active', 'system'),
    ('RUBBER', 'active', 'system'),
    ('ELECTRONICS &ELECTRICAL', 'active', 'system'),
    ('HOSPITAL/HEALTH', 'active', 'system'),
    ('KNITTING AND DYING', 'active', 'system'),
    ('RICE AND DAL SORTING', 'active', 'system'),
    ('WW END CUSTOMER - 7½" & Above', 'active', 'system'),
    ('WW END CUSTOMER - 4½" & 6½"', 'active', 'system'),
    ('WW END CUSTOMER - 6½"', 'active', 'system'),
    ('WW END CUSTOMER - 4½"', 'active', 'system'),
    ('CEMENT', 'active', 'system'),
    ('OXYGEN GENERATORS', 'active', 'system'),
    ('Retreading Solutions', 'active', 'system'),
    ('POLYMER & SYNTHETICS INDUSTRY', 'active', 'system'),
    ('PET BOTTLING', 'active', 'system'),
    ('MEDICAL EQUIPMENT & BIOTECH ENGINEERING', 'active', 'system'),
    ('PETROLEUM & OIL INDUSTRIES', 'active', 'system'),
    ('GLASS, FIBRE AND CERAMICS', 'active', 'system'),
    ('GENERAL ENGINEERING - WOOD WORK', 'active', 'system'),
    ('ENTERTAINMENT GROUPS', 'active', 'system'),
    ('AERONAUTICS', 'active', 'system'),
    ('FMCG', 'active', 'system'),
    ('GENERAL ENGINEERING - WIND MILL FABRICATORS', 'active', 'system'),
    ('JEWELLERY', 'active', 'system'),
    ('SUGAR', 'active', 'system'),
    ('WW END CUSTOMER', 'active', 'system'),
    ('CB DRILLING', 'active', 'system'),
    ('DRILLING APPLICATION', 'active', 'system'),
    ('MARBLE MINING', 'active', 'system'),
    ('SPINNING - TEXTILES', 'active', 'system'),
    ('WEAVING- AIR JET LOOMS - TEXTILES', 'active', 'system'),
    ('OEM', 'active', 'system'),
    ('Consultant', 'active', 'system'),
    ('EPC', 'active', 'system'),
    ('Trader', 'active', 'system');
